spring.application.name=OrderFlow
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=springuser
spring.datasource.password=order-flow
spring.jpa.hibernate.ddl-auto=update